# Generated by Django 3.1.2 on 2020-10-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_id', models.PositiveIntegerField()),
                ('passenger_name', models.CharField(max_length=50)),
                ('contact_data', models.TextField(max_length=50)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='airtrans.booking')),
            ],
        ),
    ]
