# Generated by Django 3.1.2 on 2020-10-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_auto_20201016_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
